### ISSUE TITLE
Liste de fiches (revue design)

### ISSUE THREAD

**Issue by CoralieCotonPro** [betagouv/seves#176]
- pas de filet autour du tableau 
- toute la ligne est cliquable
- dans la création d'une fiche on peut chercher dans le déroulant nuisible, peut on appliquer le meme champ aux filtres ?
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/seves/issues/206
- [ ] https://github.com/betagouv/seves/issues/182
```

**Comment by Anto59290** [comment]
> pas de filet autour du tableau

Le filet c'est la bordure pour toi ? Je pense qu'on peut la retirer mais elle est de manière native dans le composant

> dans la création d'une fiche on peut chercher dans le déroulant nuisible, peut on appliquer le meme champ aux filtres ?

Qu'est ce que tu en pense @alanzirek je crois que l'idée serait d'appliquer choiceJS à tous les champs des filtres. J'ai l'impression que c'est quand même un peu de travail, je ne sais pas si ça ne va pas poser problème au niveau des tests E2E existants.

**Comment by alanzirek** [comment]
@Anto59290 Je pense qu'il faut l'ajouter uniquement pour le champs organisme nuisible car la liste est assez longue.
Je ne vois pas l'utilité de l'appliquer aux autres champs dans le formulaire de recherche (région, état).

**Comment by CoralieCotonPro** [comment]
je plussoie la réponse d'Alan
après je crois qu'il y avvait une histoire d'attendre le composant dsfr ?
le composant intégré est quand meme bof bof avec la mention press to select
qui sert a rien et les items sont mega espacés
juste pour le mvp soit on met se composant a chaque fois qu'on a un
organisme nuisible soit on le met nul part ?

*Coralie COTON*
Designer | beta.gouv.fr
T. 06 81 53 66 51


Le jeu. 18 juil. 2024 à 09:20, Alan Zirek ***@***.***> a
écrit :

**Comment by CoralieCotonPro** [comment]
pour la bordure du tableau je crois que ce qui est chelou aussi c'est que
ça flotte a mort a l'intérieur, quand on aura toutes les colonnes ça me
chquera peut etre moins, peut etre qu'on peut juste mettre un gris plus
clair ?

*Coralie COTON*
Designer | beta.gouv.fr
T. 06 81 53 66 51

**Comment by alanzirek** [comment]
> juste pour le mvp soit on met se composant a chaque fois qu'on a un
organisme nuisible soit on le met nul part ?

@CoralieCotonPro techniquement le mettre nul part est bien plus arrangeant mais on avait validé avec le métier la nécessité de pouvoir rechercher un organisme nuisible car difficilement envisageable pour un agent d'aller chercher dans la longue liste du champ le bon organisme nuisible.
Donc je pense qu'on peut mettre à minima se composant externe en attendant celui du DSFR pour les organismes nuisibles.
J'ai créé l'issue dans ce sens -> https://github.com/betagouv/seves/issues/182

> pour la bordure du tableau je crois que ce qui est chelou aussi c'est que ça flotte a mort a l'intérieur, quand on aura toutes les colonnes ça me chquera peut etre moins, peut etre qu'on peut juste mettre un gris plus clair ? 

@CoralieCotonPro Je comprends pas ce que tu veux dire par flottement à l'intérieur du tableau ?

**Comment by CoralieCotonPro** [comment]
@alanzirek ok pour organisme nuisible !
pour le tableau, quand je dis que ça flotte c'est que les éléments ne sont pas calés car ils ont un trop grand écart les uns entre les autres, quand on aura toutes les colonnes (type de fiche, date de création, visibilité, liaisons) ça sera plus dense.
d'ailleurs je me rend compte qu'on avait dit qu'on virait la région car la structure créatrice embarque le nom de la région (draaf Centre Val de Loire par exemple). Par contre je vois sur la recette que c'est possible de faire DAAF Réunion en Pays de la Loire, ce n'est peut etre pas souhaitable ?

**Comment by alanzirek** [comment]
@CoralieCotonPro Si car on parle de DAAF pour les départements et régions d'outre-mer et de DRAAF en métropole.

**Comment by alanzirek** [comment]
> Par contre je vois sur la recette que c'est possible de faire DAAF Réunion en Pays de la Loire, ce n'est peut etre pas souhaitable ?

@CoralieCotonPro Si, car on parle de DAAF pour les départements et régions d'outre-mer et de DRAAF en métropole.

**Comment by alanzirek** [comment]
> Par contre je vois sur la recette que c'est possible de faire DAAF Réunion en Pays de la Loire, ce n'est peut etre pas souhaitable ?

Il ne me semble pas que c'est un prérequis côté métier.

**Comment by CoralieCotonPro** [comment]
@alanzirek que la DAAF réunion puisse créer une détection à nantes ???

**Comment by alanzirek** [comment]
> [@alanzirek](https://github.com/alanzirek) que la DAAF réunion puisse créer une détection à nantes ???

oui, pour moi il n'y a pas de vérification automatique à faire entre la structure du créateur de la fiche et les lieux. 
D'autant plus que si on va dans ce sens, il fraudrait vérifier pour la métropole : pouvoir ajouter des lieux uniquement si la commune est dans la structure du créateur.
Sachant aussi que certaines structures (MUS...) se sont pas rattachées à un département ou région.

**Comment by alanzirek** [comment]
> * toute la ligne est cliquable

J'ai ajouté le ticket #206
