### ISSUE TITLE
consulter une fiche détection (revue design)

### ISSUE THREAD

**Issue by CoralieCotonPro** [betagouv/seves#178]
Général : 
- possible de dire : si je consulte la fiche pour la première fois alors elle est en vue "détail" et a partir de la 2eme consulation elle s'affiche toujours en mode synthèse ?
- si je choisis de mettre la fiche en mode synthèse mon choix doit etre enregistré pour toute la durée de ma session et les suivantes
- ajouter les icones fermer ouvrir dans le toggle vue détail / synthèse
- le tag de type de fiche s'affiche sous le titre 

lieux : 
- les cartes doivent avoir un petit oeil pour voir le détail 
- les cartes des lieux doivent afficher le type de lieu 

Prélèvements : 
- les cartes des prélèvements doivent afficher le résutat postif/negatif
- les cartes des prélèvements doivent afficher la date

Mode synhèse : 
- les descripteurs essentiels doivent etre en colonne (cf maquette)

bloc de suivi /général : 
- L'animation de "slide" pour le passage d'un onglet a l'autre n'est pas adaptée , pas de transition
- le bloc de suivi lorsqu'il est vide peut-il avoir une hauteur minimale ? 
- 

![Image](https://github.com/user-attachments/assets/1d9e2bf6-eace-48b2-97f7-0ba7e57d8739)

```[tasklist]
### Tasks
- [ ] #193 
- [ ] #194 
- [ ] #199
- [ ] #159 
- [ ] #200 
```

**Comment by alanzirek** [comment]
@CoralieCotonPro 

Pour les points suivants, j'ai ajouté les issues (cf. liste Tasks): 
> * ajouter les icones fermer ouvrir dans le toggle vue détail / synthèse
> * les cartes doivent avoir un petit oeil pour voir le détail
```[tasklist]
### Tasks
- [ ] #193 
- [ ] #194 
```

----

Pour le reste : 
> * possible de dire : si je consulte la fiche pour la première fois alors elle est en vue "détail" et a partir de la 2eme consulation elle s'affiche toujours en mode synthèse ?
> 
> * si je choisis de mettre la fiche en mode synthèse mon choix doit etre enregistré pour toute la durée de ma session et les suivantes

Je propose d'attendre de voir si c'est un besoin qui remonte des agents une fois le MVP déployé.
Car techniquement, cela implique l'enregistrement de qui consulte quelle fiche et ce n'est pas le cas actuellement.
Idem pour la sauvegarde du mode détail/synthèse, c'est plutôt un nice to have actuellement.
Qu'en penses-tu ?

> * le tag de type de fiche s'affiche sous le titre

Il me semble qu'on avait dit qu'on supprimé ce tag car cela fait doublon avec le titre principal "Fiche détection" non ?


> * les cartes des lieux doivent afficher le type de lieu
On a supprimé le type de lieu dans le formulaire d'ajout d'un lieu. Sauf erreur de ma part, je pense que c'est la maquette qui n'est pas à jour.

WIP

**Comment by Anto59290** [comment]
Salut :)

Je peux aider un peu pour avancer sur la liste, voir fiche 2024.41 en recette:

## Déployé en recette a vérifier:
-  Ajouter les icones fermer ouvrir dans le toggle vue détail / synthèse
- Lieu : les cartes doivent avoir un petit oeil pour voir le détail
-  les cartes des prélèvements doivent afficher le résutat postif/negatif
-  les cartes des prélèvements doivent afficher la date
- mode synthèse : les descripteurs essentiels doivent etre en colonne (cf maquette)
- bloc de suivi /général : L'animation de "slide" pour le passage d'un onglet a l'autre n'est pas adaptée , pas de transition
- le bloc de suivi lorsqu'il est vide peut-il avoir une hauteur minimale ?
   

## A voir si a faire avant MVP
1 - possible de dire : si je consulte la fiche pour la première fois alors elle est en vue "détail" et a partir de la 2eme consulation elle s'affiche toujours en mode synthèse ?
2 - si je choisis de mettre la fiche en mode synthèse mon choix doit etre enregistré pour toute la durée de ma session et les suivantes
3 - le tag de type de fiche s'affiche sous le titre
4 - lieux :les cartes des lieux doivent afficher le type de lieu
