### ISSUE TITLE
Revoir la contrainte contact_has_structure_or_agent du modèle Contact 

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#198]
Supprimer le blank=True dans le modèle `Contact`.

**Comment by alanzirek** [comment]
@Anto59290 

Si je laisse la contrainte blank=True pour les champs `structure` et `agent` du modèle `Contact`, la contrainte `contact_has_structure_or_agent` est bien respectée :
![image](https://github.com/user-attachments/assets/3a2216da-3cb0-4385-96d0-2ba90ea932a1)

Si je la supprime, la contrainte `contact_has_structure_or_agent` n'est pas respectée car je dois mettre une valeur dans les champs `structure` et `agent` : 
![image](https://github.com/user-attachments/assets/a7a2d54d-f57e-4178-8ed7-e94104023aea)

Doit-on vraiment supprimer le blank=True pour les champs `structure` et `agent` du modèle `Contact` ?

**Comment by tglatt** [comment]
@Anto59290 @alanzirek ?

**Comment by alanzirek** [comment]
@tglatt je regarde ça
