### ISSUE TITLE
Refonte de l'interface des liens libre (Permettre de supprimer un lien libre)

### ISSUE THREAD

**Issue by Anto59290** [betagouv/seves#249]

**Comment by Anto59290** [comment]
@CoralieCotonPro @tglatt je n'ai pas retrouvé le design pour cette fonctionnalité.

**Comment by CoralieCotonPro** [comment]
ce n'est effectivement plus a jour dans les maquettes mais je pense qu'il serait logique d'utiliser le même composant que celui intégré par Alan pour rattacher une détection 
<img width="575" alt="Capture d’écran 2024-11-04 à 11 40 59" src="https://github.com/user-attachments/assets/dbc7b27e-9b40-43ca-8639-0226d510ebd1">
<img width="568" alt="Capture d’écran 2024-11-04 à 11 41 09" src="https://github.com/user-attachments/assets/a1089429-6de8-4f59-8a73-d706731335f2">
<img width="555" alt="Capture d’écran 2024-11-04 à 11 41 13" src="https://github.com/user-attachments/assets/c8e03545-f408-4291-929b-2cc17e59f600">

ce qui veut dire qu'il faut bien qu'on ai le bloc liens libres en mode modification

**Comment by Anto59290** [comment]
:thinking: Ok est ce que ça annule et remplace la modale existante pour les liens libres depuis la page de détail d'une fiche ou ça vient en complément ?

**Comment by tglatt** [comment]
- Suppression de la modale
- Suppression de l'action dans le menu déroulant
- rendre accessible la brique lien libre dans le formulaire de création et modification
- utiliser le composant avec le bouton suppression ci-dessus
