### ISSUE TITLE
Ajouter le nombre de lien dans le tableau (liste des fiches)

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#297]
Pour la zone : le nombre de détection + lien libre
Pour une fiche détection: la zone si il y en a + le nombre de lien libre

**Comment by CoralieCotonPro** [comment]
@tglatt je propose cette règle pour l'affichage des liens dans  les listes : 

[lien figma](https://www.figma.com/design/pSqjfGCzzBxTu4b9v28LWY/S%C3%A8ves-OK?node-id=3016-5821&t=7PHBRzN3zmwlpWC5-1)

**- Détection :** 
- lien = la zone 
- l'icone est un map marker 
- + 1 (cliquable vers la zone si il y a une zone) 
- + 0 (non cliquable si pas de zone)

**- Zone :** 
- lien = le nombre de détections rattachées 
- l'icone est une arborescence 
- + nombre de détections rattachées (non cliquable si au moins une) 
- + 0 (non cliquable si pas de détections mais est-ce possible ???)

ça veut dire qu'on ne prend pas en compte les liens libres dans le tableau car j'ai l'impression qu'en terme métier cela pourrait induire une complexité d'interpréétation

ça remet en cause le format "toute la ligne entière est cliquable" mais je pense que le tooltip sur les ON tronqués le fait déjà ?

**Comment by CoralieCotonPro** [comment]
@tglatt edit suite a nos changes. Voici la proposition envisageé pour l'affichage des lignes détections et zones dans le tableau de liste.

[Figma](https://www.figma.com/design/pSqjfGCzzBxTu4b9v28LWY/S%C3%A8ves-OK?node-id=3016-5821&t=LS6Q7m3WpoUWLXg0-1) 

- Modifications pour toutes les lignes : 
+ la ligne complète n'est plus cliquable (mais on conserve le changement de bg au hover si possible)
+ le numéro de fiche récupère un style de lien (bleu france souligné), il est cliquable et mène a la dite fiche 

- Détection : 
+ lorsqu'une zone est liée on affiche ZONE [numéro] comme un lien (bleu france souligné), il est cliquable et mène a la dite fiche 
+ lorsque pas de zone = vide

- Zone : 
+ lien = le nombre de détections rattachées
+ l'icone est une arborescence
+ si nombre de détections ≥ 1 alors on affiche le nombre de détections (non cliquable)
+ nombre de détection = 0 ne devrait pas être possible ?

**Comment by tglatt** [comment]
@CoralieCotonPro , Je trouve ça  dommage de ne pas avoir le même comportement entre fiche zone et détection (surtout si elles finissent dans le même tableau).
Tu as fait un essaie avec l'icon de géolocation ?

**Comment by CoralieCotonPro** [comment]
![line](https://github.com/user-attachments/assets/165c9ca6-8178-4b47-b894-283b58ae4e80)
je pense qu'on aura quand même un petit soucis d'affordance de la cliquabilité (a tes souhaits !) sur le lien de la zone mais attendons de voir

**Comment by tglatt** [comment]
Ticket dans notion
