### ISSUE TITLE
Consulter la liste des documents (triées par date antéchronologique automatiquement)

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#32]

**Comment by CoralieCotonPro** [comment]
@alanzirek 
- les cartes sont trop grosses ils fautt réduire les typos je vois par exemple le titre du doc en 20pts au lieu de 14, foncion devrait etre en 12 ainsi que le tag etc
- le commentaire doit etre en tooltip

**Comment by Anto59290** [comment]
@CoralieCotonPro Corrigé en recette je te laisse me dire si c'est ok pour toi
