### ISSUE TITLE
Génération d'un changelog et gestion des versions de Sèves

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#339]
## Spécifications
Nous allons avoir besoin de suivre les évolutions afin de communiquer les modifications au fur et à mesure des mise à jour de l'application.

Pourrait-on utiliser un génération de changelog qui s'appuie sur le [conventional commit](https://pypi.org/project/conventional-commit/)?

**Comment by Anto59290** [comment]
Je ne suis pas vraiment favorable à ce genre de convention car le fait d'ajouter des "tags / types / metadata" dans le titre rend difficile de faire tenir les titres des messages de commit en 50 caractères plus ou moins, qui est la norme que j'utilise en général pour que le titre soit lisible dans toutes les interfaces.

Cf mes derniers commits sur le repo (tiré de git log):

Permettre d'avoir des laboratoires inactifs
Permettre de choisir l'espèce dans une liste
Corriger la saisie d'un lieu sans commune
Ajouter le numéro Resytal dans les prélèvements
Améliorer les performances de la vue de liste

**Comment by tglatt** [comment]
Le besoin est d'avoir un changelog accessible par tous et les non devs.
Rajouter feat(sv), fix(ssa) ne rallonge pas beaucoup le.commit, si?

**Comment by tglatt** [comment]
On abandonne cette idée. Le tag sera manuel et on récupérera les commits avec `git diff`
