### ISSUE TITLE
Proposition workflow de déploiement et environnement

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#340]
## Spécifications
Nous allons probablement avoir besoin de trois environnements:
- un environnement de dev / recette
- un environnement de pre-prod pour réaliser les formations et les tests avec les utilisateurs
- un environnement de production

- L'environnement de dev est mis à jour à chaque commit
- L'environnement de pre-prod est mis à jour à la création d'un tag d'une nouvelle version (cf #339 )
- L'environnement de prod est mis manuellement à jour à partir du pipeline du tag

**Comment by tglatt** [comment]
@Anto59290 , tu en penses quoi?

**Comment by Anto59290** [comment]
:wave: Je pense que c'est trop environments pour le moment.  Je pense que pour le moment le setup suivant serait suffisant:
- Un envrionnement (dev, test, preprod, recette peu importe le nom) mis à jour a chaque commit pour nos tests en interne et éventuellement tests utilisateurs
- Un environnement de prod

Plus d'environnements c'est aussi plus de maintenance et de configuration a faire, plus de gestion des accès, etc.

**Comment by Anto59290** [comment]
:thinking: Je ne suis pas sur de comprendre, le deploiement d'un commit n'est pas sensé faire planter l'environnement.

**Comment by tglatt** [comment]
S'il n'y a pas de downtime, effectivement ca se discute mais ce n'est ce que nous avons observé avec scalingo sur.une stack nextjs. 
C'est a la suite de redéploiement pendant les formations qu'on a fini par faire.un environnement de démo.
Et il y a aussi la question d'avoir un environnement stable en terme de fonctionnalité. Je me mets à la place de la personne qui fait la démo...

**Comment by alanzirek** [comment]
Pour info, j'ai déjà commencé la configuration (nom de domaine, app scalingo, portail EAP...) d'un environnement de démo suite à une discussion avec @CoralieCotonPro sur tchap (cf. channel produit) et du besoin d'avoir un environnement "clean" pour les démos.
Mais je peux le supprimer si on change d'avis.

**Comment by tglatt** [comment]
Après discussion, on garde deux environnements:
- dev / recette (déploiement à chaque commit)
- production (Le déploiement sur tag)

pour l'environnement de démo, on attend d'avoir du recul.
