### ISSUE TITLE
Ajout d'une Structure > Affichage de la valeur au lieu du label

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#342]
<img width="554" alt="Capture d’écran 2024-10-23 à 20 36 33" src="https://github.com/user-attachments/assets/43511738-8ff5-4f39-9ad7-7ea3ca7b5f6e">

**Comment by Anto59290** [comment]
:wave: Je n'ai pas compris le changement attendu. Quel est le résultat attendu sur cette page qui est en capture d'écran ? Peut être que ça parlera plus a @alanzirek ?

**Comment by tglatt** [comment]
C'est service_account qui est affiché et non Service account, c'est normal?

**Comment by Anto59290** [comment]
Je vois ce que tu veux dire, pas sur que ça soit volontaire en effet.

**Comment by Anto59290** [comment]
J'ai regardé un peu le code et ça a l'air bien volontaire:
```
niveau1_choices = Structure.objects.values_list("niveau1", flat=True).distinct().order_by("niveau1")
self.fields["structure_niveau1"].choices = [(niveau1, niveau1) for niveau1 in niveau1_choices]
self.fields["structure_niveau1"].initial = niveau1_choices.first()
```

Peut être que j'aurais du mieux nommer le niveau 1 du service_account et/ou qu'on devrait le masquer dans tous les cas ? @alanzirek

**Comment by alanzirek** [comment]
Oui c'est normal. Pour pouvoir ajouter une structure à la liste des contacts, on doit d'abord sélectionner le niveau 1 (AC, DDPP, SRAL...).
service_account est de niveau 1 et c'est la valeur qui a en base.
Il me semble que service_account a été ajouté pour pouvoir lier des objets existants en bd (message, document...).
Mais ça sera pas utile pour la prod.
@Anto59290 oui je pense qu'on peut le masquer
