### ISSUE TITLE
Prélèvement > déplacer le numéro phytopass au dessus de prélèvement officiel

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#373]
Un numéro phytopass doit pouvoir être enregistré seulement s'il s'agit d'une prélèvement officiel.

**Comment by tglatt** [comment]
Ce n'est pas le contraire? 

un numéro phytopass peut être renseigné même si ce n'est pas un prélèvement officiel.

**Comment by tglatt** [comment]
@alanzirek ?

**Comment by alanzirek** [comment]
Je sèche sur cette question :) Peut-être relancer le métier sur la question (cf. mail - Suite travail BDD - adaptation fiches et valences etc. + corrections de la BDD pour reprise)

**Comment by tglatt** [comment]
Ce champ va être supprimé...
