### ISSUE TITLE
Déplacer le champ Nombre ou volume de végétaux infestés dans la fiche détection

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#376]
Actuellement, le champ `Nombre ou volume de végétaux infestés` est lié à une fiche zone délimité mais doit être lié à une fiche détection.

**Comment by tglatt** [comment]
@alanzirek , peut-on mettre le lien au dessus du champs commentaire

![Image](https://github.com/user-attachments/assets/b1adb812-56e5-4fc7-bb2a-4d97efce7bf7)
