### ISSUE TITLE
Barre de recherche | reprise de l'UI

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#390]
Barre de recherche
- adapter la largeur des champs de recherche
- bouton recherche l’un en dessous de l’autre

Sur les petits écrans:

<img width="1424" alt="Capture d’écran 2024-11-12 à 18 03 15" src="https://github.com/user-attachments/assets/fe7b93c9-7429-45b0-b1fa-3ab5a687da85">

**Comment by CoralieCotonPro** [comment]
Pour la barre de recherche je propose la règle suivante :

**Comment by tglatt** [comment]
sur notion...
