### ISSUE TITLE
Header | ajout de lien vers l'index des fiches

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#392]
Le logo et le tag `Santé des végétaux` ramènent a l’index des fiches

![Image](https://github.com/user-attachments/assets/d0cb9895-017c-43a5-b3d7-7aa4a8fffe95)

**Comment by tglatt** [comment]
@alanzirek , on avait parlé que le logo soit cliquable aussi vendredi

**Comment by alanzirek** [comment]
> @alanzirek , on avait parlé que le logo soit cliquable aussi vendredi

ah désolé j'ai pas fait attention. Je corrige ça.
