### ISSUE TITLE
Tableau des fiches | modification de l'UI

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#393]
- [x] supprimer le titre `Liste des fiches`
- [x] réduire les espaces horizontaux (dans le but d’avoir plus de lignes affichées dans la liste)
- [x] réduire la colonne numéro de fiche
- [x] ON ne fait que deux lignes maximum, après on tronque avec `...`.
- [ ] On voir le nom de complet de l'ON dans un tooltip
- [ ] ajouter un tooltip sur icône cloche => `notifié a l’AC`

Sur petit écran:
<img width="1322" alt="Capture d’écran 2024-11-12 à 18 24 15" src="https://github.com/user-attachments/assets/5b7a8ba0-b289-4ce7-bb1e-491d9a44a77e">

**Comment by tglatt** [comment]
@Anto59290 , peut-on utiliser un fr-link et modifier le class `fr-link` uniquement pour le tableau?

**Comment by Anto59290** [comment]
C'est ce que je proposais en écrivant `on devra donc écraser les règles du DSFR pour retourner à des règles textes`(désolé si ce n'était pas clair). C'est possible mais je ne garanti pas le rendu du composant tooltop qui n'a pas du tout été prévu pour ce genre de situation

**Comment by tglatt** [comment]
si ca te va, tu tentes et on voit le résultat

**Comment by CoralieCotonPro** [comment]
Au SRAL d'angers ils ont dit que c'était primordial d'avoir la totalité du nom qui s'affiche. en effet les ON ont un nom latin + un petit nom "français" mai les noms latin sont a cours de refonte (BDD EPPO global database mise a jour au fil de l'eau) donc ils ont non seulement besoin d'avoir toute la ligne visible mais EN PLUS dans les champs combo search/déroulant il faut que ça cherche dans tous les termes même ceux entre parenthèses. sur ce dernier point je ne suis pas sure du comportement j'ai fait le test et ça marche pas a tous les coups . exemple : enroulement chlorotique de l’abricotier vs candidatus phytoplasma prunorum

**Comment by Anto59290** [comment]
@tglatt je propose déjà de review/merger la PR existante et de voir les deux derniers points ensuite afin que l'on puisse déjà bénéficier des premiers changement en recette et pour la suite sans attendre d'avantage de prise de décisions

**Comment by tglatt** [comment]
Parfait @Anto59290

**Comment by tglatt** [comment]
@Anto59290 , possible de gérer `Détection` et la date sur une ligne et non deux?

![Image](https://github.com/user-attachments/assets/386d3eab-7b1f-4327-9dfa-91adafc75da0)

**Comment by Anto59290** [comment]
J'ai bien bricolé dans #414  ;)
