### ISSUE TITLE
Cohérence entre le type d’un lieu et le site d’inspection d’un prélèvement

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#400]
- Lieu > déplacer le descripteur `type` au dessous du descripteur `commune`
- Lieu > renommer le descripteur `type` en `site d'inspection`
- Prélèvement > supprimer le descripteur `site d'inspection`

**Comment by Anto59290** [comment]
J'ai proposé déjà le point "Prélèvement > supprimer le descripteur site d'inspection" dans #418. Faut que j'attaque les points 1 et 2 ;)
