### ISSUE TITLE
Fiche détection | Fiche zone > ON

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#405]
Quand on modifie l’ON d’une fiche détection doit-on:
- mettre à jour l’ON de la fiche zone à laquelle appartient la fiche détection
- mettre à jour l’ON dans les fiches détections associées à cette fiche zone

Si on ne fait pas cela, on laisse l’utilisateur créer des incohérences métiers.

**Comment by tglatt** [comment]
Pour bien faire il faudrait proposer les deux possibles principaux : 

1 - changer l'ON de cette fiche détection et de toutes les fiches en lien fonctionnel (pourrait servir à un moment de changement de nomenclature par ex.)
2 - changer l'ON de cette seule fiche détection et rompre tous les liens (hypothèse : erreur d'analyse, on croyait que c'était A mais finalement c'est B)
3 - Une dernière option étant de supprimer la-dite fiche, et éventuellement de la ressaisir si c'est un autre organisme de quarantaine qui mérite d'être saisi. 

Donc avec 1 et (3 qui n'est pas une fonctionnalité spécifique mais existe), on s'en sort! Mais il faudra des warning +++ avant validation !

**Comment by tglatt** [comment]
@CoralieCotonPro , cela nécessite une maquette, non?

**Comment by CoralieCotonPro** [comment]
@tglatt au moins faire valider l'enchainement des warning et des wordings précis oui, je prends le point

**Comment by CoralieCotonPro** [comment]
@tglatt voici [la maquette figma ](https://www.figma.com/proto/PbTadee9BL8eYKhCJpKGc3/Changement-ON?page-id=0%3A1&node-id=3-374&node-type=frame&viewport=-1382%2C-326%2C1&t=Vtfmns6XfCPzzVQy-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3%3A374) du parcours de modification d'un ON depuis une détection qui a des liens fonctionnels.

l'idée est de proposer les deux solutions (rompre les liens ou tout modifier) avec des warning +++

**Comment by tglatt** [comment]
Retour dev:
Idéalement une action à part. Car plus ça va aller plus la modif de fiche va être impacté. Aujourd'hui on peut modifiier la fiche, mais aussi ses lieux et ses prélévements, mais aussi les liens libres, ça fait déjà 4 types d'objets à gérer avec des subtilités en plus (en fonction du bouton c'est brouillon ou publié, etc.).

**Comment by CoralieCotonPro** [comment]
je suis d'accord je vais reprendre le sujet dans ce sens

**Comment by CoralieCotonPro** [comment]
donc voici le[ figma ](https://www.figma.com/proto/PbTadee9BL8eYKhCJpKGc3/Changement-ON?page-id=25%3A88&node-id=25-292&node-type=frame&viewport=-272%2C450%2C0.5&t=r6QA29W1uIP9mFam-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=25%3A292v)

et j'explique les détail sur [ce loom](https://www.loom.com/share/dd9d4eeffef64850ab223093a77958e3?sid=afb54269-9257-4f61-bae6-333e91ef4e7d)
