### ISSUE TITLE
Gestion de l'état brouillon des fiches détection

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#408]
Dans le cas d'une fiche détection en brouillon:
- [x] la fiche ne comporte pas de bloc de suivi 
-> #479 
- [x] en mode ~~création~~ modification, les boutons visibles sont : `enregistrer brouillon` et `publier` 
-> #480 
- [x] en mode visualisation les boutons visibles sont : `modifer` et `publier` 
-> #481
- [x] on supprime la modale de modification de visibilité 
- [x] en mode visualisation, la seule action accessible est `supprimer` 
-> #483
- [X] on ajoute le bloc liens libres en création et en modification 
-> #409 
- [x] dans la liste des fiches le numéro de fiche est indiqué en « non attribué » 
-> #482 
- [x] pour les liens libres : on ne propose pas les fiches en brouillon
-> #484
- [x] dans les fiches zones, on ne peut pas ajouter des fiches détection brouillon en zone infesté ou hors zone investé
-> #485

**Comment by alanzirek** [comment]
> pour les liens libres : on ne propose pas les fiches en brouillon

@tglatt Est-ce qu'on fait pareil pour les fiches zones délimitées ?
