### ISSUE TITLE
Statut reglementaire > ajout valeurs autorisées

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#429]
Ajout des valeurs:
 - Organismes temporairement réglementés
 - Organismes émergents

Dans les status reglementaires

**Comment by Anto59290** [comment]
@tglatt je pense qu'on peut mettre ce ticket pour le soft launch non ? Est ce que pour les code je mets ce que je veux (OTR et OE ?) où il y a une règle a respecter ?

**Comment by tglatt** [comment]
je ne trouve rien OTR et OE, ca doit être ça :-)
