### ISSUE TITLE
Fiche détection > affichage code OEPP

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#437]
Ne pas afficher le préfixe `OP_`

![Image](https://github.com/user-attachments/assets/2c8a8765-8421-4e26-9009-3f448b18048c)

**Comment by Anto59290** [comment]
Aujourd'hui c'est stocké avec le OE_ en base, est ce qu'on ne nettoyerais pas la base plutôt que de faire un fix à l'affichage ? Pour quelle raison on a le OE_ en base et on ne le veux pas a l'affichage ? @tglatt

**Comment by tglatt** [comment]
Si on peut virer le `OE_` en base de données c'est mieux! Je sais pas pourquoi il est là...

**Comment by tglatt** [comment]
![Image](https://github.com/user-attachments/assets/91f4589a-7ebe-49f0-b4b8-97280e5184f6)
