### ISSUE TITLE
synthése/detail fiche zone

### ISSUE THREAD

**Issue by CoralieCotonPro** [betagouv/seves#444]
le principe de plié/dééplié detail synthese doit etre implémenté sur la fiche zone. on garde en descripteurs principaux : 
- risque (ON + statut réglementaire)
- infos  (créateur + date)
- commentaire

**Comment by CoralieCotonPro** [comment]
@tglatt voici ma proposition pour la vue synthèse de la zone : 
On affiche comme descripteurs essentiels :

**Comment by tglatt** [comment]
cf notion
