### ISSUE TITLE
identification des champs obligatoires / facultatifs

### ISSUE THREAD

**Issue by CoralieCotonPro** [betagouv/seves#445]
d'une manière ou d'une autre les champs obligatoires ou facultatifs doivent etre identifiables par les utilisateurs.
la position du dsfr 
`Etant donnée qu’il faut limiter le nombre d’information à demander aux utilisateurs, les informations optionnelles doivent être limitées au maximum. Ainsi, les champs sont obligatoires par défaut, et les champs optionnels apparaissent avec une information “(optionnel)” dans le label.
Une mention explicative doit se trouver au dessus du formulaire afin d’en informer l’utilisateur : “Sauf mention contraire “(optionnel)” dans le label, tous les champs sont obligatoires“`

MAIS comme Sèves fonctionne a l'inverse, a savoir avec le maximum de champs non obligatoires je propose de faire ce qui suit.
- ajouter sur toutes les pages de formulaires (y compris les modales) la mention "“Sauf mention contraire “(obligatoire)” dans le label, tous les champs sont optionnels“`
- ajouter la mention (obligatoire) en toutes lettres et entre parenthèses

**Comment by tglatt** [comment]
mis coté de notion
