### ISSUE TITLE
Fiche zone > enlever l’UI spécifique du rayon tampon règlementaire

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#455]
![Image](https://github.com/user-attachments/assets/3f0a9f19-d3ea-47eb-95c0-16d5f9c74e9c)

**Comment by Anto59290** [comment]
@tglatt uniquement en édition ou aussi en visualisation (car il a aussi une UI spécifique en visualisation)![Image](https://github.com/user-attachments/assets/08637318-45ce-4900-b038-e77a5741ecae)

**Comment by tglatt** [comment]
pour les deux...
