### ISSUE TITLE
Fiche détection > Coordonnées GPS

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#457]
On ne veut conserver que un système de coordonnées. Nous avons choisit de conserver le système WS84:
- migration de toutes les coordonnées en base de données dans le sytème WS84
- suppression du système lambert en base de données et dans le formulaire
- dans l'import des données, convertir toutes les coordonnées dans le système WS84

**Comment by tglatt** [comment]
Ca marche @alanzirek , on peut merge alors

**Comment by tglatt** [comment]
je note un ticket pour @Anto59290 pour l'import

**Comment by tglatt** [comment]
@alanzirek , le champ est toujours visible dans le formulaire

![Image](https://github.com/user-attachments/assets/5a7995ee-7f34-4f59-81cb-3dcc00f60bd9)

**Comment by alanzirek** [comment]
@tglatt oubli corrigé dans la PR #507
