### ISSUE TITLE
UI > Mise en place d'un composant information 

### ISSUE THREAD

**Issue by tglatt** [betagouv/seves#460]
- Choix d'un composant d'information
- Utilisation de ce composant dans les ci-dessous:
 - `Pour ajouter une prélèvement vous devez avoir renseigné au moins un lieu.`
 
<img width="881" alt="Capture d’écran 2024-11-19 à 12 28 23" src="https://github.com/user-attachments/assets/398a745e-711b-42ea-ac89-0e6b07bd1715">

**Comment by CoralieCotonPro** [comment]
je propose d'utiliser le composant information du DSFR
