### ISSUE TITLE
Gestion des statuts règlementaires de chaque organisme nuisible

### ISSUE THREAD

**Issue by alanzirek** [betagouv/seves#64]
Dans la création et l'édition d'une fiche zone:
- sélectionner automatiquement le statut reglementaire selon le tableur excel joint.
- Si l'ON n'est pas dans le fichier, enlever la valeur dans le statut reglementaire

Pour info, on va mettre à jour le fichier de concordance ON <-> statut reglementaire de temps en temps. C'est bien si c'est un CSV accessible dans Github

[ON_Statut.xlsx](https://github.com/user-attachments/files/17717658/ON_Statut.xlsx)

**Comment by Anto59290** [comment]
@tglatt pour moi le status Organisme émergent n'existe pas en base, @alanzirek j'ai raté un truc ? Est ce que l'on doit créer ce nouveau status?

**Comment by alanzirek** [comment]
> @tglatt pour moi le status Organisme émergent n'existe pas en base, @alanzirek j'ai raté un truc ?

@Anto59290 Non il n'existe pas en base. Voici la liste des status ajoutés en base : 
https://github.com/betagouv/seves/blob/2f64ef1b243459aea55bb7ba95167b6029ecabb2/sv/migrations/0002_insert_initial_data.py#L748-L753

> Est ce que l'on doit créer ce nouveau status?

Je pense mais à voir avec le métier pour confirmation (cc @tglatt)

**Comment by tglatt** [comment]
Pour le statut `Organisme émergent`, la question est coté métier. On attend le retour.

dans le ticket, il est noté:
>Si l'ON n'est pas dans le fichier, enlever la valeur dans le statut reglementaire

Ce n'a pas été fait mais je me demande si c'est une bonne idée. Des avis?

**Comment by alanzirek** [comment]
Tu masques le champ statut réglementaire dans le formulaire si l'ON n'est pas dans le fichier, c'est bien ça ?

**Comment by tglatt** [comment]
Retour métier:
Il faut avoir les valences:
- Organismes de quarantaine
- Organismes de quarantaine prioritaires
- Organismes de quarantaine de zone protégée
- Organismes temporairement réglementés `A AJOUTER`
- Organismes réglementés non de quarantaine
- Organismes émergents `A AJOUTER`

Par ailleurs, le comportement ci-dessous est à implémenter:
>Si l'ON n'est pas dans le fichier, enlever la valeur dans le statut reglementaire

\cc @Anto59290
